
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sam JunYi
 */
public class AdminModify extends javax.swing.JFrame {

    /**
     * Creates new form AdminManagement
     */
    public AdminModify() {
        initComponents();
        
    }

private List<String[]> readDataFromFile(String filename) throws IOException {
    List<String[]> data = new ArrayList<>();
    File file = new File(filename);
    
    if (!file.exists()) {
        return data;
    }

    try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
        // 跳过表头行
        reader.readLine();
        // 跳过分隔线
        reader.readLine();
        
        String line;
        while ((line = reader.readLine()) != null) {
            String[] rowData = line.split(" \\| ");
            data.add(rowData);
        }
    }
    return data;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        ATable = new javax.swing.JTable();
        javax.swing.JButton ADelete = new javax.swing.JButton();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        APassword = new javax.swing.JPasswordField();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        AEmail = new javax.swing.JTextField();
        AUserID = new javax.swing.JTextField();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        AContact = new javax.swing.JTextField();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        AName = new javax.swing.JTextField();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        AUsername = new javax.swing.JTextField();
        javax.swing.JButton AClear = new javax.swing.JButton();
        javax.swing.JButton ARegister = new javax.swing.JButton();
        ABack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Admin Management");

        ATable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserID", "Name", "Username", "Email", "Contact"
            }
        ));
        jScrollPane1.setViewportView(ATable);

        ADelete.setBackground(new java.awt.Color(255, 204, 51));
        ADelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ADelete.setText("Delete");
        ADelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADeleteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("Password:");

        APassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APasswordActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("Email:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel9.setText("User ID:AXXXX");

        AEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AEmailActionPerformed(evt);
            }
        });

        AUserID.setText("A");
        AUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AUserIDActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("Contact number :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Registeration Admin :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("Name:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setText("Username :");

        AUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AUsernameActionPerformed(evt);
            }
        });

        AClear.setBackground(new java.awt.Color(204, 204, 204));
        AClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AClear.setText("Clear");
        AClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AClearActionPerformed(evt);
            }
        });

        ARegister.setBackground(new java.awt.Color(204, 204, 204));
        ARegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ARegister.setText("Register");
        ARegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ARegisterActionPerformed(evt);
            }
        });

        ABack.setBackground(new java.awt.Color(204, 204, 204));
        ABack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ABack.setText("Back");
        ABack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ARegister)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ABack)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ADelete)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AName, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addComponent(AUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(APassword, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(AContact))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(APassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADelete)
                    .addComponent(ARegister)
                    .addComponent(AClear)
                    .addComponent(ABack))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ADeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADeleteActionPerformed
        int row = ATable.getSelectedRow();

        if (row < 0){
            JOptionPane.showMessageDialog(this,
                "Please enter all fields",
                "Try again",
                JOptionPane.ERROR_MESSAGE);
        } else{
            DefaultTableModel model = (DefaultTableModel) ATable.getModel();
            model.removeRow(row);
        }
    }//GEN-LAST:event_ADeleteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
DefaultTableModel model = (DefaultTableModel) ATable.getModel();
    model.setRowCount(0); // 清空现有数据
    
    try (BufferedReader reader = new BufferedReader(new FileReader("Admin.txt"))) {
        // 跳过表头行和分隔线
        reader.readLine(); // 表头
        reader.readLine(); // 分隔线
        
        String line;
        while ((line = reader.readLine()) != null) {
            String[] rowData = line.split(" \\| "); // 按分隔符拆分
            model.addRow(rowData);
        }
    } catch (IOException ex) {
        // 文件不存在时创建新文件是正常的，不需要打印错误
        if (!(ex instanceof FileNotFoundException)) {
            ex.printStackTrace();
        }
    }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void AEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AEmailActionPerformed

    private void AUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AUserIDActionPerformed

    private void AUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AUsernameActionPerformed

    private void AClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AClearActionPerformed
        AUserID.setText("");
        AName.setText("");
        AUsername.setText("");
        APassword.setText("");
        AEmail.setText("");
        AContact.setText("");
        
    }//GEN-LAST:event_AClearActionPerformed

    private void ARegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ARegisterActionPerformed
        String userID = AUserID.getText();
        String Name = AName.getText();
        var Username = AUsername.getText();
        String Password = APassword.getText();
        String Email = AEmail.getText();
        var Contact = AContact.getText();


        if (userID.isEmpty()||Name.isEmpty()||Username.isEmpty()||Password.isEmpty()||Email.isEmpty()||Contact.isEmpty()){
            JOptionPane.showMessageDialog(this,
                "Please enter all fields",
                "Try again",
                JOptionPane.ERROR_MESSAGE);

        }else{
            DefaultTableModel model = (DefaultTableModel) ATable.getModel();
            model.addRow(new Object[]{userID,Name,Username,Password,Email,Contact});

            AUserID.setText("");
            AName.setText("");
            AUsername.setText("");
            APassword.setText("");
            AEmail.setText("");
            AContact.setText("");
            
        }

    }//GEN-LAST:event_ARegisterActionPerformed

    private void APasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_APasswordActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
DefaultTableModel model = (DefaultTableModel) ATable.getModel();
Vector<Vector> tableData = model.getDataVector();

try (BufferedWriter writer = new BufferedWriter(new FileWriter("Admin.txt"))) {
    // Write column headers
    for (int col = 0; col < model.getColumnCount(); col++) {
        writer.write(model.getColumnName(col));
        if (col < model.getColumnCount() - 1) {
            writer.write(",");  // Changed from " | " to comma
        }
    }
    writer.newLine();
    
    // Write data rows
    for (Vector row : tableData) {
        for (int col = 0; col < row.size(); col++) {
            // Handle potential commas in data by wrapping in quotes
            String value = row.get(col).toString();
            if (value.contains(",")) {
                value = "\"" + value + "\"";
            }
            writer.write(value);
            if (col < row.size() - 1) {
                writer.write(",");  // Changed from " | " to comma
            }
        }
        writer.newLine();
    }
    
    JOptionPane.showMessageDialog(this, 
        "Data saved successfully to Admin.txt",
        "Save Complete",
        JOptionPane.INFORMATION_MESSAGE);
} catch (IOException ex) {
    JOptionPane.showMessageDialog(this,
        "Error saving data: " + ex.getMessage(),
        "Save Error",
        JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_formWindowClosing

    private void ABackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABackActionPerformed
    formWindowClosing(new java.awt.event.WindowEvent(this, java.awt.event.WindowEvent.WINDOW_CLOSING));
    
    // Then proceed with the original code
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Dashboard().setVisible(true);
        }
    });
    this.dispose();
    }//GEN-LAST:event_ABackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminModify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ABack;
    private javax.swing.JTextField AContact;
    private javax.swing.JTextField AEmail;
    private javax.swing.JTextField AName;
    private javax.swing.JPasswordField APassword;
    private javax.swing.JTable ATable;
    private javax.swing.JTextField AUserID;
    private javax.swing.JTextField AUsername;
    // End of variables declaration//GEN-END:variables
}
