package Student;



import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;



/**
 *
 * @author Sam JunYi
 */
public class StudentDashboard extends javax.swing.JFrame {
    private String userID;
    /**
     * Creates new form Dashboard
     */
    public StudentDashboard(String userID) {
        initComponents();
        this.userID = userID;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        SButton1 = new javax.swing.JButton();
        SButton2 = new javax.swing.JButton();
        SButton3 = new javax.swing.JButton();
        SButton4 = new javax.swing.JButton();
        SButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dashboard");

        SButton1.setBackground(new java.awt.Color(204, 204, 204));
        SButton1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        SButton1.setText("View Class Schedule");
        SButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SButton1ActionPerformed(evt);
            }
        });

        SButton2.setBackground(new java.awt.Color(204, 204, 204));
        SButton2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        SButton2.setText("Subject Enrollment");
        SButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SButton2ActionPerformed(evt);
            }
        });

        SButton3.setBackground(new java.awt.Color(204, 204, 204));
        SButton3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        SButton3.setText("View Payment");
        SButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SButton3ActionPerformed(evt);
            }
        });

        SButton4.setBackground(new java.awt.Color(204, 204, 204));
        SButton4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        SButton4.setText("Updated Profile");
        SButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SButton4ActionPerformed(evt);
            }
        });

        SButton5.setBackground(new java.awt.Color(204, 204, 204));
        SButton5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        SButton5.setText("Exit");
        SButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel1)
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SButton2ActionPerformed
    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectEnrollment(userID).setVisible(true);
            }
        });
    this.dispose();
    }//GEN-LAST:event_SButton2ActionPerformed

    private void SButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SButton1ActionPerformed
    java.awt.EventQueue.invokeLater(() -> {
            new ClassSchedule(userID).setVisible(true);
            });
    this.dispose();
    }//GEN-LAST:event_SButton1ActionPerformed

    private void SButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SButton3ActionPerformed
     String fileName = "py_status.txt";
    
    // Ask user for name input
    String name = JOptionPane.showInputDialog(this, 
        "Enter the name to check payment status:",
        "Payment Status Check",
        JOptionPane.QUESTION_MESSAGE);
    
    if (name == null || name.trim().isEmpty()) {
        return; // User clicked cancel or entered nothing
    }

    try (BufferedReader reader = new BufferedReader(new FileReader(fileName))) {
        StringBuilder result = new StringBuilder();
        boolean found = false;
        
        // Skip header line
        String header = reader.readLine();
        
        // Read file line by line
        String line;
        while ((line = reader.readLine()) != null) {
            // Split by comma and trim whitespace
            String[] parts = line.split("\\s*,\\s*");
            
            // Check if this line matches the requested name (4 parts expected)
            if (parts.length >= 4 && parts[0].equalsIgnoreCase(name.trim())) {
                found = true;
                result.append("Payment Record:\n")
                      .append("Name: ").append(parts[0]).append("\n")
                      .append("Amount Payable: ").append(parts[1]).append("\n")
                      .append("Total Collected: ").append(parts[2]).append("\n")
                      .append("Status: ").append(parts[3]).append("\n\n");
            }
        }
        
        // Show results
        if (found) {
            JOptionPane.showMessageDialog(this,
                result.toString(),
                "Payment Status for " + name,
                JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                "No payment records found for: " + name,
                "Not Found",
                JOptionPane.WARNING_MESSAGE);
        }
        
    } catch (FileNotFoundException e) {
        JOptionPane.showMessageDialog(this,
            "Payment records file not found: " + fileName,
            "File Missing",
            JOptionPane.ERROR_MESSAGE);
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this,
            "Error reading payment records: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_SButton3ActionPerformed

    private void SButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SButton5ActionPerformed
        int response = JOptionPane.showConfirmDialog(
        this, 
        "Are you sure you want to exit the system?",
        "Exit Confirmation",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);
    
    // If user clicked Yes
    if (response == JOptionPane.YES_OPTION) {
        // Close the current window
        this.dispose();
        
        // Or exit the entire application
        System.exit(0);
    }
    }//GEN-LAST:event_SButton5ActionPerformed

    private void SButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SButton4ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateProfile(userID).setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_SButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Dashboard(userID).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SButton1;
    private javax.swing.JButton SButton2;
    private javax.swing.JButton SButton3;
    private javax.swing.JButton SButton4;
    private javax.swing.JButton SButton5;
    // End of variables declaration//GEN-END:variables
}
