package Tutor;


import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author wei sheng
 */
public class ManageClassInfoGui extends javax.swing.JFrame {
    private String currentuserID;
    private DefaultTableModel model;
    
    /**private DefaultTableModel model;
     * Creates new form ManageClassInfoGui
     */
    public ManageClassInfoGui(String userID) {
        initComponents();
        
        this.currentuserID = userID;
//        String currentuserID = LoginPage.loggedInUserID;
        
        model = (DefaultTableModel) tableClassInfo.getModel();
        loadClassInfoFile(currentuserID);
      
        loadTutorSubjects(currentuserID);
    }
    private void loadTutorSubjects(String userID) {
  
    comsubject.removeAllItems();  // 清空旧的 subject
    try (BufferedReader br = new BufferedReader(new FileReader("tutor.txt"))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] parts = line.split(",");
            if (parts.length >= 8 && parts[0].equals(userID)) {
                String subjects = parts[7].trim();  // 第 8 项是 subject（用 | 分隔）
                String[] subjectList = subjects.split("\\|");  // 记得用双反斜杠转义 |
                for (String subject : subjectList) {
                    comsubject.addItem(subject.trim());
                }
            }
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
}

    private void loadClassInfoFile(String userID){
            DefaultTableModel model = (DefaultTableModel) tableClassInfo.getModel();
    model.setRowCount(0); // 清空表格

    try (BufferedReader br = new BufferedReader(new FileReader("ClassInfo.txt"))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] parts = line.split(",");
            if (parts.length >= 8) {
                String recordTutorID = parts[7].trim(); // 第8项是UserID
                if (recordTutorID.equals(userID)) {
                    model.addRow(new Object[] {
                        parts[0], // Class ID
                        parts[1], // Subject
                        parts[2], // Course Date
                        parts[3], // Course Time
                        parts[4], // Location
                        parts[5], // Fee
                        parts[6], // Tutor Name
                        parts[7]  // User ID (tutorID)
                    });
                }
            }
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JButton btnADD = new javax.swing.JButton();
        javax.swing.JButton btnClear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfFee = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfTutorName = new javax.swing.JTextField();
        comsubject = new javax.swing.JComboBox<>();
        cbCourseDay = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbCourseMonth = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbCourseYears = new javax.swing.JComboBox<>();
        cbCourseTime = new javax.swing.JComboBox<>();
        cbLocation = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClassInfo = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        tfSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(977, 690));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("List of Class Information");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Class", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel3.setText("Subject");

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel4.setText("Course Day");

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel5.setText("Course Time");

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel6.setText("Location");

        btnADD.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnADD.setText("ADD");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        jLabel7.setText("Fee");

        tfFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFeeActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe Print", 3, 12)); // NOI18N
        jLabel8.setText("Tutor Name");

        tfTutorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTutorNameActionPerformed(evt);
            }
        });

        comsubject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-{select one}-", "Chinese", "English", "Bahasa Melayu", "Sejarah", "Physics", "Biology", "Chemistry", "Mathematics" }));
        comsubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comsubjectActionPerformed(evt);
            }
        });

        cbCourseDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", " " }));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel2.setText("Month");

        cbCourseMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel9.setText("Years");

        cbCourseYears.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        cbCourseTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4:00-5:00PM", "5:00-6:00PM", "6:00-7:00PM", "7:00-8:00PM", "8:00-9:00PM", "9:00-10:00PM", "10:00-11:00PM", " " }));

        cbLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Room A", "Room B", "Room C", "Room D", "Room E", "Online" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btnADD, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 52, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comsubject, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfTutorName)
                            .addComponent(tfFee)
                            .addComponent(cbCourseDay, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbCourseYears, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbCourseMonth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbCourseTime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbLocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnADD, btnClear});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comsubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCourseDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbCourseMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbCourseYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbCourseTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addComponent(tfFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfTutorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnADD)
                    .addComponent(btnClear))
                .addGap(16, 16, 16))
        );

        jButton3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tableClassInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Class ID", "Subject", "Course Date", "Course Time", "Location", "Fee", "Tutor Name", "User ID"
            }
        ));
        jScrollPane1.setViewportView(tableClassInfo);

        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int row = tableClassInfo.getSelectedRow();
        
        if(row < 0){
            JOptionPane.showMessageDialog(this,
                    "No row is selected! Please select one row",
                    "Select row", JOptionPane.ERROR_MESSAGE);
        }else{
            DefaultTableModel model = (DefaultTableModel) tableClassInfo.getModel();
            model.removeRow(row);
        }
        try{
            BufferedWriter bw = new BufferedWriter(new FileWriter("ClassInfo.txt"));
            DefaultTableModel model = (DefaultTableModel) tableClassInfo.getModel();

            for(int i = 0; i< model.getRowCount(); i++){
                StringBuilder sb = new StringBuilder();
                for(int j = 0; j<model.getColumnCount(); j++){
                    Object cell = model.getValueAt(i, j);
                    sb.append(cell != null ? cell.toString().trim(): ""); 
                    if(j< model.getColumnCount() - 1){
                        sb.append(",");
                }

                }
                bw.write(sb.toString());
                bw.newLine();
            }

        bw.close();
        System.out.println("Data saved to ClassInfo.txt on Window close");
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
  
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        try{
//        BufferedReader br = new BufferedReader(new FileReader("ClassInfo.txt"));
//        DefaultTableModel model = (DefaultTableModel) tableClassInfo.getModel();
//        model.setRowCount(0);
//
//        String line;
//        while((line = br.readLine()) != null){
//            String[] rowData = line.split(",");
//            Vector <Object> row = new Vector<>();
//            
//            for(int i = 0; i< rowData.length; i++){
//                row.add(rowData[i]);
//            }
//            model.addRow(row);
//        }
//
//            br.close();
//        }catch(Exception ex){
//            JOptionPane.showMessageDialog(this,"Error: "+ ex.getMessage());
//        }
    }//GEN-LAST:event_formWindowOpened

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        tfFee.setText("");
        tfTutorName.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
    String subject = comsubject.getSelectedItem().toString().trim();
    String day = cbCourseDay.getSelectedItem().toString().trim();
    String month = cbCourseMonth.getSelectedItem().toString();
    String year = cbCourseYears.getSelectedItem().toString();
    String courseDate = year + "-" 
                      + (month.length()==1?"0"+month:month) + "-" 
                      + (day.length()==1?"0"+day:day);
    String time       = cbCourseTime.getSelectedItem().toString();
    String location   = cbLocation.getSelectedItem().toString();
    String fee = tfFee.getText().trim();
    String userID = currentuserID; 
    String tutorName = tfTutorName.getText().trim();

    
      // 2. Basic non-empty validation
    if (subject.equals("-{select one}-") || fee.isEmpty() || tutorName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields");
        return;
    }


    // 3. 自动生成 Class ID，如 C001、C002…
    DefaultTableModel model = (DefaultTableModel) tableClassInfo.getModel();
    int rowCount = model.getRowCount();
    String classID = String.format("C%03d", rowCount + 1);

    // 4. 检查是否重复（可选）
    for (int i = 0; i < rowCount; i++) {
        if (model.getValueAt(i, 0).toString().equals(classID)) {
            classID = String.format("C%03d", rowCount + 2); // 避免重复
        }
    }
    
     boolean conflict = false;
    if (!location.equalsIgnoreCase("Online")) {
        try (BufferedReader br = new BufferedReader(new FileReader("ClassInfo.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length < 7) continue;

                String existingDate     = parts[2];  // stored as yyyy-MM-dd
                String existingTime     = parts[3];
                String existingLocation = parts[4];

                // Only check conflicts when the stored location matches the chosen one
                if (existingLocation.equalsIgnoreCase(location)) {
                    // Conflict if same date
                    if (existingDate.equals(courseDate)) {
                        JOptionPane.showMessageDialog(this,
                            "Date conflict at the same location. Please choose another date.",
                            "Conflict", JOptionPane.WARNING_MESSAGE);
                        conflict = true;
                        break;
                    }
                    // Or conflict if same time
                    if (existingTime.equals(time)) {
                        JOptionPane.showMessageDialog(this,
                            "Time conflict at the same location. Please choose another time.",
                            "Conflict", JOptionPane.WARNING_MESSAGE);
                        conflict = true;
                        break;
                    }
                }
            }
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Error reading ClassInfo.txt!",
                "File Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }
    if (conflict) {
        return;  // 若检测到冲突，则直接返回
    }
    
    // 5. 添加到 JTable
    Object[] row = {
        classID,
        subject,
        courseDate,
        time,
        location,
        fee,
        tutorName,
        userID
    };
    model.addRow(row);

    // 6. 写入文件（追加方式）
     try (BufferedWriter bw = new BufferedWriter(new FileWriter("ClassInfo.txt", true))) {
        bw.write(String.join(",",
            classID, subject, courseDate, time, location, fee, tutorName, userID
        ));
        bw.newLine();
    } catch (IOException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this,
            "Error writing to ClassInfo.txt!",
            "File error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 7. 清空输入字段
    tfFee.setText("");
    tfTutorName.setText("");
    comsubject.setSelectedIndex(0);

    // 8. 成功提示
    JOptionPane.showMessageDialog(this, "Class information added successfully.");
    }//GEN-LAST:event_btnADDActionPerformed

    private void tfFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFeeActionPerformed

    private void tfTutorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTutorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTutorNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TUTORDASHBOARDPAGE page = new TUTORDASHBOARDPAGE(currentuserID);
        page.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        DefaultTableModel ob= (DefaultTableModel) tableClassInfo.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(ob);
        tableClassInfo.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(tfSearch.getText()));
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
       
    }//GEN-LAST:event_tfSearchActionPerformed

    private void comsubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comsubjectActionPerformed

    }//GEN-LAST:event_comsubjectActionPerformed
//    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String []args) {
//      
//
//
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ManageClassInfoGui().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbCourseDay;
    private javax.swing.JComboBox<String> cbCourseMonth;
    private javax.swing.JComboBox<String> cbCourseTime;
    private javax.swing.JComboBox<String> cbCourseYears;
    private javax.swing.JComboBox<String> cbLocation;
    private javax.swing.JComboBox<String> comsubject;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableClassInfo;
    private javax.swing.JTextField tfFee;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfTutorName;
    // End of variables declaration//GEN-END:variables
}












