
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sam JunYi
 */
public class AdminModify extends javax.swing.JFrame {
    private String currentUserID = "A001";
    private String[] originalAdminData;

    /**
     * Creates new form AdminManagement
     */
    public AdminModify() {
        initComponents();
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        ATable = new javax.swing.JTable();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        APassword = new javax.swing.JPasswordField();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        AEmail = new javax.swing.JTextField();
        AUserID = new javax.swing.JTextField();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        AContact = new javax.swing.JTextField();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        AName = new javax.swing.JTextField();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        AUsername = new javax.swing.JTextField();
        javax.swing.JButton AClear = new javax.swing.JButton();
        javax.swing.JButton AUpdate = new javax.swing.JButton();
        ABack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin Management");

        ATable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserID", "Name", "Username", "Email", "Contact"
            }
        ));
        jScrollPane1.setViewportView(ATable);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password:");

        APassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APasswordActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("User ID:AXXX");

        AEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AEmailActionPerformed(evt);
            }
        });

        AUserID.setEditable(false);
        AUserID.setText("<default>");
        AUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AUserIDActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact number :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin Modify");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Username :");

        AUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AUsernameActionPerformed(evt);
            }
        });

        AClear.setBackground(new java.awt.Color(204, 204, 204));
        AClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AClear.setText("Clear");
        AClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AClearActionPerformed(evt);
            }
        });

        AUpdate.setBackground(new java.awt.Color(204, 204, 204));
        AUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AUpdate.setText("Update");
        AUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AUpdateActionPerformed(evt);
            }
        });

        ABack.setBackground(new java.awt.Color(204, 204, 204));
        ABack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ABack.setText("Back");
        ABack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ABack)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AName, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addComponent(AUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(APassword, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(AContact))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(APassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AUpdate)
                    .addComponent(AClear)
                    .addComponent(ABack))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private boolean validateInputs() {
    // Name validation
    if (AName.getText().trim().isEmpty()) {
        showError("Please enter your name", "Name Required", AName);
        return false;
    }
    if (!AName.getText().matches("^[a-zA-Z ]+$")) {
        showError("Name can only contain letters and spaces", "Invalid Name", AName);
        return false;
    }

    // Username validation
    if (AUsername.getText().trim().isEmpty()) {
        showError("Please enter a username", "Username Required", AUsername);
        return false;
    }
    if (!AUsername.getText().matches("^[a-zA-Z0-9_]{4,20}$")) {
        showError("Username must be 4-20 characters (letters, numbers, underscores)", "Invalid Username", AUsername);
        return false;
    }

    // Password validation (only if changed)
    String password = new String(APassword.getPassword());
    if (!password.isEmpty()) {
        if (password.length() < 8) {
            showError("Password must be at least 8 characters", "Weak Password", APassword);
            return false;
        }
        if (!password.matches(".*[A-Z].*")) {
            showError("Password must contain at least one uppercase letter", "Weak Password", APassword);
            return false;
        }
        if (!password.matches(".*[0-9].*")) {
            showError("Password must contain at least one number", "Weak Password", APassword);
            return false;
        }
    }

    // Email validation
    if (AEmail.getText().trim().isEmpty()) {
        showError("Please enter your email", "Email Required", AEmail);
        return false;
    }
    if (!AEmail.getText().matches("^[\\w.-]+@[\\w.-]+\\.[a-z]{2,}$")) {
        showError("Please enter a valid email address", "Invalid Email", AEmail);
        return false;
    }

    // Contact validation
    if (AContact.getText().trim().isEmpty()) {
        showError("Please enter your contact number", "Contact Required", AContact);
        return false;
    }
    if (!AContact.getText().matches("^\\d{10,15}$")) {
        showError("Contact must be 10-15 digits", "Invalid Contact", AContact);
        return false;
    }

    return true;
}

private void showError(String message, String title, JComponent field) {
    JOptionPane.showMessageDialog(this, message, title, JOptionPane.ERROR_MESSAGE);
    field.requestFocus();
}
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
DefaultTableModel model = (DefaultTableModel) ATable.getModel();
        model.setRowCount(0);
        
        try (BufferedReader reader = new BufferedReader(new FileReader("Admin.txt"))) {
            String header = reader.readLine(); // Read and ignore header
            
            String line;
            while ((line = reader.readLine()) != null) {
                String[] rowData = line.split(",");
                if (rowData.length >= 6) { // Ensure we have all fields
                    model.addRow(new Object[]{
                        rowData[0], // UserID
                        rowData[1], // Name
                        rowData[2], // Username
                        rowData[4], // Email
                        rowData[5]  // Contact
                    });
                    
                    // Load current admin's data into form
                    if (rowData[0].equals(currentUserID)) {
                        originalAdminData = rowData.clone();
                        AUserID.setText(rowData[0]);
                        AName.setText(rowData[1]);
                        AUsername.setText(rowData[2]);
                        APassword.setText(""); // Don't show password
                        AEmail.setText(rowData[4]);
                        AContact.setText(rowData[5]);
                    }
                }
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, 
                "Error loading admin data: " + ex.getMessage(),
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void AEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AEmailActionPerformed

    private void AUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AUserIDActionPerformed

    private void AUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AUsernameActionPerformed

    private void AClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AClearActionPerformed
        AUserID.setText("");
        AName.setText("");
        AUsername.setText("");
        APassword.setText("");
        AEmail.setText("");
        AContact.setText("");
        
    }//GEN-LAST:event_AClearActionPerformed

    private void AUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AUpdateActionPerformed
    if (!AUserID.getText().equals(currentUserID)) {
            JOptionPane.showMessageDialog(this, 
                "You can only update your own profile", 
                "Access Denied", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
    if (!validateInputs()) {
        return;
    }

        // Get and validate inputs
        String name = AName.getText().trim();
        String password = new String(APassword.getPassword()).trim();
        String email = AEmail.getText().trim();
        String contact = AContact.getText().trim();

        if (name.isEmpty() || email.isEmpty() || contact.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "All fields are required", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Update the table
        DefaultTableModel model = (DefaultTableModel) ATable.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).equals(currentUserID)) {
                model.setValueAt(name, i, 1);
                model.setValueAt(email, i, 3);
                model.setValueAt(contact, i, 4);
                break;
            }
        }
        
        JOptionPane.showMessageDialog(this, 
            "Profile updated (will be saved when closing)", 
            "Success", 
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_AUpdateActionPerformed

    private void APasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_APasswordActionPerformed
private void saveAdminData() {
        DefaultTableModel model = (DefaultTableModel) ATable.getModel();
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("Admin.txt"))) {
            // Write header
            writer.write("UserID,Name,Username,Password,Email,Contact\n");
            
            // Write data
            for (int i = 0; i < model.getRowCount(); i++) {
                String password = originalAdminData != null && 
                                model.getValueAt(i, 0).equals(currentUserID) ?
                                (new String(APassword.getPassword()).isEmpty() ? 
                                    originalAdminData[3] : 
                                    new String(APassword.getPassword())) :
                                "password"; // Default for other admins
                
                writer.write(String.format("%s,%s,%s,%s,%s,%s\n",
                    model.getValueAt(i, 0),
                    model.getValueAt(i, 1),
                    model.getValueAt(i, 2),
                    password,
                    model.getValueAt(i, 3),
                    model.getValueAt(i, 4)
                ));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                "Error saving data: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
}
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
if (evt.getSource() == this) { // Only save if the event comes from this window
            saveAdminData();
        }
    }//GEN-LAST:event_formWindowClosing

    private void ABackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABackActionPerformed
    formWindowClosing(new java.awt.event.WindowEvent(this, java.awt.event.WindowEvent.WINDOW_CLOSING));
    
    // Then proceed with the original code
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Dashboard().setVisible(true);
        }
    });
    this.dispose();
    }//GEN-LAST:event_ABackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminModify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ABack;
    private javax.swing.JTextField AContact;
    private javax.swing.JTextField AEmail;
    private javax.swing.JTextField AName;
    private javax.swing.JPasswordField APassword;
    private javax.swing.JTable ATable;
    private javax.swing.JTextField AUserID;
    private javax.swing.JTextField AUsername;
    // End of variables declaration//GEN-END:variables
}
