
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Vector;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sam JunYi
 */
public class ManageTutor extends javax.swing.JFrame {

    /**
     * Creates new form RegisterTutor
     */
    public ManageTutor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RTutorLevel = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        RTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        javax.swing.JButton RRegister = new javax.swing.JButton();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        RUserID = new javax.swing.JTextField();
        javax.swing.JButton RDelete = new javax.swing.JButton();
        RContact = new javax.swing.JTextField();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        RUsername = new javax.swing.JTextField();
        RPassword = new javax.swing.JPasswordField();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        REmail = new javax.swing.JTextField();
        javax.swing.JButton RClear = new javax.swing.JButton();
        RGC = new javax.swing.JRadioButton();
        RName = new javax.swing.JTextField();
        RSubject = new javax.swing.JTextField();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        RGA = new javax.swing.JRadioButton();
        RGB = new javax.swing.JRadioButton();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        ABack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setMinimumSize(new java.awt.Dimension(1080, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        RTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserID", "Name", "Username", "Password", "Email", "Contact", "Level", "Subject"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(RTable);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("User ID:TXXX");

        RRegister.setBackground(new java.awt.Color(204, 204, 204));
        RRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RRegister.setText("Register");
        RRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RRegisterActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact number:");

        RUserID.setEditable(false);
        RUserID.setText("<default>");
        RUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RUserIDActionPerformed(evt);
            }
        });

        RDelete.setBackground(new java.awt.Color(255, 204, 51));
        RDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RDelete.setText("Delete");
        RDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDeleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registeration Tutor :");

        RUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RUsernameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email:");

        REmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REmailActionPerformed(evt);
            }
        });

        RClear.setBackground(new java.awt.Color(204, 204, 204));
        RClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RClear.setText("Clear");
        RClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RClearActionPerformed(evt);
            }
        });

        RTutorLevel.add(RGC);
        RGC.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        RGC.setForeground(new java.awt.Color(255, 255, 255));
        RGC.setText("Not on both");
        RGC.setActionCommand("GC");
        RGC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RGCActionPerformed(evt);
            }
        });

        RSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RSubjectActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Subject :");

        RTutorLevel.add(RGA);
        RGA.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        RGA.setForeground(new java.awt.Color(255, 255, 255));
        RGA.setText("Bachelor's Degree Certificate");
        RGA.setActionCommand("GA");
        RGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RGAActionPerformed(evt);
            }
        });

        RTutorLevel.add(RGB);
        RGB.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        RGB.setForeground(new java.awt.Color(255, 255, 255));
        RGB.setText(" Associate Degree Diploma");
        RGB.setActionCommand("GB");
        RGB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RGBActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Select Tutor Level:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username :");

        ABack.setBackground(new java.awt.Color(204, 204, 204));
        ABack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ABack.setText("Back");
        ABack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RGA)
                            .addComponent(RGB)
                            .addComponent(RGC)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(RUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(RPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(RName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel3)
                                                    .addComponent(RUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(REmail, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(RContact, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(RRegister)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RClear)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ABack)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RDelete)
                                        .addGap(31, 31, 31))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RRegister)
                            .addComponent(RClear)
                            .addComponent(RDelete)
                            .addComponent(ABack)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(REmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RGA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RGB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RGC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        RGB.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RGAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RGAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RGAActionPerformed

    private void RGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RGBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RGBActionPerformed

    private void RGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RGCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RGCActionPerformed

    private void RUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RUsernameActionPerformed

    private void REmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REmailActionPerformed

    private void RSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RSubjectActionPerformed

    private void RDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDeleteActionPerformed
        int row = RTable.getSelectedRow();
        
        if (row < 0){
            JOptionPane.showMessageDialog(this,
                    "Please enter all fields",
                    "Try again",
                    JOptionPane.ERROR_MESSAGE);
        } else{
            DefaultTableModel model = (DefaultTableModel) RTable.getModel();
            model.removeRow(row);
        }
    }//GEN-LAST:event_RDeleteActionPerformed

    private void RRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RRegisterActionPerformed
    // Auto-generate UserID
    String UserID = generateNextTutorID();
    RUserID.setText(UserID);  // Display generated ID
    
    // Get input values
    String Name = RName.getText().trim();
    String Username = RUsername.getText().trim();
    String Password = new String(RPassword.getPassword()).trim(); // For JPasswordField
    String Email = REmail.getText().trim();
    String Contact = RContact.getText().trim();
    String Subject = RSubject.getText().trim();
    
    // Get selected tutor level
    String level = null;
    if (RTutorLevel.getSelection() != null) {
        level = RTutorLevel.getSelection().getActionCommand();
    }
    
    // Validate inputs
    if (Name.isEmpty()) {
        showError("Please enter tutor name", "Missing Name");
        RName.requestFocus();
        return;
    }
    
    if (Username.isEmpty() || Username.contains(" ")) {
        showError("Username cannot be empty or contain spaces", "Invalid Username");
        RUsername.requestFocus();
        return;
    }
    
    if (Password.length() < 8) {
        showError("Password must be at least 8 characters", "Weak Password");
        RPassword.requestFocus();
        return;
    }
    
    if (!isValidEmail(Email)) {
        showError("Please enter a valid email address", "Invalid Email");
        REmail.requestFocus();
        return;
    }
    
    if (!Contact.matches("\\d{10,15}")) {
        showError("Contact must be 10-15 digits only", "Invalid Contact");
        RContact.requestFocus();
        return;
    }
    
    if (level == null) {
        showError("Please select tutor level", "Level Required");
        return;
    }
    
    if (Subject.isEmpty()) {
        showError("Please enter subject specialization", "Subject Required");
        RSubject.requestFocus();
        return;
    }
    
    // Add to table
    DefaultTableModel model = (DefaultTableModel) RTable.getModel();
    model.addRow(new Object[]{UserID, Name, Username, Password, Email, Contact, level, Subject});
    
    // Clear form
    clearTutorForm();
    
    // Generate next ID
    RUserID.setText(generateNextTutorID());
    
    // Show success
    showSuccess("Tutor registered successfully! ID: " + UserID);
}

// Helper methods
private String generateNextTutorID() {
    DefaultTableModel model = (DefaultTableModel) RTable.getModel();
    int maxID = 0;
    
    for (int i = 0; i < model.getRowCount(); i++) {
        String id = model.getValueAt(i, 0).toString();
        if (id.matches("T\\d{3}")) { // T001, T002 format for tutors
            int num = Integer.parseInt(id.substring(1));
            maxID = Math.max(maxID, num);
        }
    }
    return String.format("T%03d", maxID + 1);
}

private boolean isValidEmail(String email) {
    return email.matches("^[\\w.-]+@[\\w.-]+\\.[a-z]{2,}$");
}

private void showError(String message, String title) {
    JOptionPane.showMessageDialog(this, message, title, JOptionPane.ERROR_MESSAGE);
}

private void showSuccess(String message) {
    JOptionPane.showMessageDialog(this, message, "Success", JOptionPane.INFORMATION_MESSAGE);
}

private void clearTutorForm() {
    RName.setText("");
    RUsername.setText("");
    RPassword.setText("");
    REmail.setText("");
    RContact.setText("");
    RTutorLevel.clearSelection();
    RSubject.setText("");

    }//GEN-LAST:event_RRegisterActionPerformed

    private void RClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RClearActionPerformed

        RName.setText("");
        RUsername.setText("");
        RPassword.setText("");
        REmail.setText("");
        RContact.setText("");
        RTutorLevel.clearSelection();
        RSubject.setText("");
    }//GEN-LAST:event_RClearActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    DefaultTableModel model = (DefaultTableModel) RTable.getModel();
    Vector<Vector> tableData = model.getDataVector();

    try (BufferedWriter writer = new BufferedWriter(new FileWriter("tutor.txt"))) {

        for (int col = 0; col < model.getColumnCount(); col++) {
            writer.write(model.getColumnName(col));
            if (col < model.getColumnCount() - 1) {
                writer.write(",");  
            }
        }
        writer.newLine();
        
       
        for (Vector row : tableData) {
            for (int col = 0; col < row.size(); col++) {
                writer.write(row.get(col).toString());
                if (col < row.size() - 1) {
                    writer.write(",");  // 改为逗号
                }
            }
            writer.newLine();
        }
    } catch (IOException ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    DefaultTableModel model = (DefaultTableModel) RTable.getModel();
    model.setRowCount(0); // 清空现有数据
    
    try (BufferedReader reader = new BufferedReader(new FileReader("tutor.txt"))) {
        // 读取表头行 (跳过不处理)
        reader.readLine();
        
        String line;
        while ((line = reader.readLine()) != null) {
            String[] rowData = line.split(","); // 按逗号拆分
            model.addRow(rowData);
        }
    } catch (IOException ex) {
        // 文件不存在时创建新文件是正常的，不需要打印错误
        if (!(ex instanceof FileNotFoundException)) {
            ex.printStackTrace();
        }
    }
    }//GEN-LAST:event_formWindowOpened

    private void ABackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABackActionPerformed
    formWindowClosing(new java.awt.event.WindowEvent(this, java.awt.event.WindowEvent.WINDOW_CLOSING));
    
    // Then proceed with the original code
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Dashboard().setVisible(true);
        }
    });
    this.dispose();
    }//GEN-LAST:event_ABackActionPerformed

    private void RUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RUserIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageTutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ABack;
    private javax.swing.JTextField RContact;
    private javax.swing.JTextField REmail;
    private javax.swing.JRadioButton RGA;
    private javax.swing.JRadioButton RGB;
    private javax.swing.JRadioButton RGC;
    private javax.swing.JTextField RName;
    private javax.swing.JPasswordField RPassword;
    private javax.swing.JTextField RSubject;
    private javax.swing.JTable RTable;
    private javax.swing.ButtonGroup RTutorLevel;
    private javax.swing.JTextField RUserID;
    private javax.swing.JTextField RUsername;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
